#!/bin/bash

#SECOND APPROACH IS MORE FASTER IG LIKE MAX IS 0.03 INSTEAD OF 0.04 A LITTLE BIT FASTER
mapfile -t all_files < <(find . -type f -name "*.c") #mapfile stores the res of find to an array

for file in "${all_files[@]}"; do #going through array 
    new_file="$file.orig" #get the copyname
    if cp "$file" "$new_file"; then #if copy ok
        echo "Copied $file to $new_file successfully"
    else
        echo "Failed to copy $file to $new_file"
    fi
done

